name: Update Recent Activity

on:
  schedule:
    # සෑම පැය 2 කට වරක් ස්වයංක්‍රීයව ක්‍රියාත්මක වේ
    - cron: '0 */2 * * *'
  workflow_dispatch: # අවශ්‍ය විටක manual run කිරීමට හැක

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Readme-Workflows/recent-activity@v2.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
